//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordCounterClient.WordCounterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WordCounterService.IWordCounterService")]
    public interface IWordCounterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordCounterService/Count", ReplyAction="http://tempuri.org/IWordCounterService/CountResponse")]
        System.Collections.Generic.Dictionary<string, int> Count(string[] text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordCounterService/Count", ReplyAction="http://tempuri.org/IWordCounterService/CountResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> CountAsync(string[] text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWordCounterServiceChannel : WordCounterClient.WordCounterService.IWordCounterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordCounterServiceClient : System.ServiceModel.ClientBase<WordCounterClient.WordCounterService.IWordCounterService>, WordCounterClient.WordCounterService.IWordCounterService {
        
        public WordCounterServiceClient() {
        }
        
        public WordCounterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordCounterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordCounterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordCounterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, int> Count(string[] text) {
            return base.Channel.Count(text);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> CountAsync(string[] text) {
            return base.Channel.CountAsync(text);
        }
    }
}
